apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
spec:
  selector:
    matchLabels:
      app: go-server
  replicas: 3
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
        - name: go-server
          image: tineto/calc:latest
          ports:
            - containerPort: 8000
